---

build:
  - 'pyproject.toml'
  - 'uv.lock'
ci:
  - '.github/changed-files-spec.yml'
  - '.github/workflows/**'
  - '.pre-commit-config.yaml'
  - 'Taskfile.yml'
docs:
  - 'docs/**'
  - '**/*.md'
  - 'mkdocs.yml'
src:
  - 'src/**'
tests:
  - 'tests/**'
