# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: waku
site_description: A Python framework for creating modular, loosely coupled, and extensible applications
site_url: https://waku-py.github.io/waku/
site_dir: site
strict: true
copyright: '&copy; 2024-2025 <a href="https://github.com/waku-py" target="_blank" rel="noopener">waku-py</a>'

# Repository
repo_name: waku-py/waku
repo_url: https://github.com/waku-py/waku

extra:
  analytics:
    provider: google
    property: G-58BG5HHK50
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/waku-py/waku
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/waku/


# Configuration
watch: [ mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, src/waku, examples ]

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  links:
    absolute_links: relative_to_docs

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - optimize
    - search.highlight
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme)"
      scheme: auto
      toggle:
        icon: material/brightness-auto
        name: Switch to Light Mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to Dark Mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to System Preference

  font:
    text: Roboto
    code: JetBrains Mono

  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - exclude:
      glob:
        - "includes/*"
        - "__pycache__/*"
        - "*.pyc"
        - "*.pyo"
        - ".git/*"
  - git-revision-date-localized:
      enabled: !ENV [ DOCS_DEPLOY, false ]
      type: timeago
      enable_creation_date: true
      fallback_to_build_date: true
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [ py, std ]
          paths: [ src ]
          options:
            docstring_style: google
            filters:
              - '!^_'
            show_signature_annotations: true
            show_root_heading: true
            show_source: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            merge_init_into_class: true
            docstring_section_style: spacy
            show_docstring_examples: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true


# Extensions
markdown_extensions:
  - abbr
  - admonition  # !!! blocks support
  - attr_list  # specify html attrs in markdown
  - md_in_html  # render md wrapped to html tags
  - tables
  - toc:
      permalink: true
      title: Table of contents
      slugify: !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
  - pymdownx.details  # admonition collapsible
  - pymdownx.emoji: # render material icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true  # allows link to codeline
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite  # inline code highlighting `#!python <code>`
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: [ !relative $config_dir ]
      check_paths: true
      auto_append:
        - docs/includes/abbreviations.md
  - pymdownx.superfences: # highlight code syntax
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true  # create tabs group
      slugify: !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
  - pymdownx.tasklist: # create task lists with `- [ ]`
      custom_checkbox: true

# Page tree
# TODO: move to literate-nav plugin
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Usage:
      - usage/providers.md
      - usage/modules.md
      - usage/lifespan.md
      - usage/cqrs.md
      - Extensions:
          - usage/extensions/index.md
          - Validation: usage/extensions/validation.md
  - Integrations:
      - ASGI: integrations/asgi.md
      - Litestar: integrations/litestar.md
  - Examples:
      - Modularity: examples/modularity.md
      - Mediator (CQRS): examples/cqrs.md
  - API Reference: reference.md
  - Contributing:
      - contributing/index.md
      - Documentation: contributing/docs.md
  - Changelog: changelog.md
