# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Waku
site_description: Microframework for building modular and loosely coupled applications
strict: false
copyright: Copyright &copy; 2025 Waku

# Repository
repo_name: waku-py/waku
repo_url: https://github.com/waku-py/waku

# Configuration
watch: [ mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, src/waku, docs/ ]

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  links:
    absolute_links: relative_to_docs

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - optimize
    - toc.follow

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - exclude:
      glob:
        - includes/*
        - __pycache__/*
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocstrings:
      handlers:
        python:
          paths: [ waku ]
          options:
            members_order: source
            separate_signature: true
            filters: [ "!^_" ]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_inheritance_diagram: true
            show_submodules: true
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [ py, std ]


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      title: Page contents
      slugify: !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      base_path: !relative $config_dir
      auto_append:
        - docs/includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Overview:
      - index.md
      - Examples:
          - examples/basic.md
          - examples/mediator.md
  - Usage:
      - usage/quickstart.md
      - usage/modules.md
      - usage/dp.md
      - usage/cqrs.md
  - Extensions:
      - extensions/lifecycle.md
      - extensions/validation.md
  - Development:
      - Contributing: contributing.md
      - Reference: reference.md
  - Changelog: changelog.md
