version: "3"

set: [ nounset ]

vars:
  SOURCES: .

env:
  COLUMNS: 120
  FORCE_COLOR: 1
  PRE_COMMIT_COLOR: always
  UV_NO_SYNC: 1  # Avoid syncing the virtual environment on `uv run`
  PYTHONPATH: .

tasks:
  default:
    cmd:
      task: all

  .uv:
    desc: Check UV installation
    internal: true
    silent: true
    preconditions:
      - sh: command -v uv > /dev/null 2>&1
        msg: "⚠️ UV not found. Install from: https://docs.astral.sh/uv/getting-started/installation/"

  .uv-locked:
    desc: Check UV lockfile status
    deps: [ .uv ]
    internal: true
    silent: true
    preconditions:
      - sh: uv lock --locked
        msg: "⚠️ Project lockfile is out of sync. Run: task deps:sync"

  deps:install:
    aliases: [ install ]
    desc: Install the package, dependencies, and pre-commit for local development
    deps: [ .uv ]
    silent: true
    cmds:
      - task: deps:sync
      - uv run prek install --install-hooks --overwrite
      - echo "✅ Development environment setup complete"

  deps:sync:
    aliases: [ sync ]
    desc: Sync all project dependencies
    deps: [ .uv ]
    silent: true
    cmds:
      - uv sync --all-extras --all-groups
      - echo "✅ Dependencies synced"

  deps:upgrade:
    aliases: [ upgrade ]
    desc: Upgrade all project dependencies and pre-commit hooks
    deps: [ .uv ]
    silent: true
    cmds:
      - uv run uv-upgrade --no-sync
      - task: deps:sync
      - uv run prek auto-update
      - uv run prek install --install-hooks --overwrite
      - echo "✅ Dependencies upgraded"

  deps:audit:
    aliases: [ security-audit ]
    desc: Audit dependencies for vulnerabilities
    deps: [ .uv-locked ]
    silent: true
    cmd: uv run pysentry-rs {{.CLI_ARGS}}

  lint:
    desc: Lint code
    deps: [ .uv-locked ]
    cmds:
      - uv run ruff check {{.CLI_ARGS}} {{.SOURCES}}
      - uv run ruff format --check {{.SOURCES}}

  format:
    aliases: [ fmt ]
    desc: Format code
    deps: [ .uv-locked ]
    cmds:
      - uv run ruff check --fix {{.SOURCES}}
      - uv run ruff format {{.SOURCES}}

  typecheck:
    desc: Run all typecheckers
    deps: [ ty, pyrefly, mypy ]

  mypy:
    desc: Type check code with MyPy
    deps: [ .uv-locked ]
    cmd: uv run mypy{{ if ne (env "MYPY_PRETTY") "0" }} --pretty{{end}} {{.SOURCES}}

  ty:
    desc: Type check code with Ty
    deps: [ .uv-locked ]
    cmds:
      - uv run ty check {{.CLI_ARGS}} {{.SOURCES}}

  pyrefly:
    desc: Type check code with pyrefly
    deps: [ .uv-locked ]
    cmds:
      - uv run pyrefly check {{.CLI_ARGS}}

  check:
    aliases: [ ci ]
    desc: Lint & typecheck python source files
    deps: [ lint, typecheck ]

  codespell:
    desc: Use Codespell to do spellchecking
    deps: [ .uv-locked ]
    cmd: uv run pre-commit run codespell --all-files

  pre-commit:
    aliases: [ prek, pre-commit-all ]
    desc: Run all pre-commit hooks against all files
    deps: [ .uv-locked ]
    silent: true
    cmd: uv run prek run --verbose --all-files --hook-stage manual

  deptry:
    desc: Find unused, missing and transitive dependencies in project
    deps: [ .uv-locked ]
    cmd: uv run deptry .

  gitlint:
    desc: Lint git commit
    deps: [ .uv ]
    cmd: uv run gitlint {{.CLI_ARGS}}

  test:
    desc: Run tests
    deps: [ .uv-locked ]
    cmd: uv run pytest {{.PYTEST_ARGS}} {{.CLI_ARGS}}

  test:cov:
    aliases: [ 'test:ci', 'test:all' ]
    desc: Run tests with coverage
    vars:
      PYTEST_ARGS: --cov
    cmds:
      - task: test
        vars:
          PYTEST_ARGS:
            ref: .PYTEST_ARGS

  all:
    desc: Run the full set of checks
    cmds:
      - task: check
      - task: codespell
      - task: test:cov

  clean:
    desc: Clear local caches and build artifacts
    cmds:
      - rm -rf `find . -name __pycache__`
      - rm -f `find . -type f -name '*.py[co]'`
      - rm -f `find . -type f -name '*~'`
      - rm -f `find . -type f -name '.*~'`
      - rm -rf `find . -name '.*cache'`
      - rm -rf .task
      - rm -rf htmlcov
      - rm -f .coverage
      - rm -f .coverage.*
      - rm -f coverage.xml
      - rm -rf *.egg-info
      - rm -rf build
      - rm -rf dist
      - rm -rf site
