version: '3'

set: [ nounset ]

vars:
  SOURCES: .

env:
  COLUMNS: 120
  FORCE_COLOR: 1
  PRE_COMMIT_COLOR: always
  UV_NO_SYNC: 1  # Avoid syncing the virtual environment on `uv run`
  PYTHONPATH: .

tasks:
  default:
    cmd:
      task: all

  .uv:
    desc: Check UV installation and lockfile status
    internal: true
    silent: true
    preconditions:
      - sh: command -v uv > /dev/null 2>&1
        msg: "⚠️ UV not found. Install from: https://docs.astral.sh/uv/getting-started/installation/"

  .uv-locked:
    desc: Check UV installation and lockfile status
    deps: [ .uv ]
    internal: true
    silent: true
    preconditions:
      - sh: uv lock --locked
        msg: "⚠️ Lockfile outdated. Run: task deps:sync"

  deps:install:
    aliases: [ install ]
    desc: Install the package, dependencies, and pre-commit for local development
    deps: [ .uv ]
    silent: true
    cmds:
      - task: deps:sync
      - uv run pre-commit install
      - echo "✅ Development environment setup complete"

  deps:sync:
    aliases: [ sync ]
    desc: Sync all project dependencies
    deps: [ .uv ]
    silent: true
    cmds:
      - uv sync --all-extras --all-groups {{.CLI_ARGS}}
      - echo "✅ Dependencies synced"

  deps:upgrade:
    aliases: [ upgrade ]
    desc: Upgrade all project dependencies and pre-commit hooks
    deps: [ .uv-locked ]
    silent: true
    cmds:
      - uv sync --all-extras --all-groups --upgrade
      - uv run pre-commit autoupdate
      - echo "✅ Dependencies upgraded"

  lint:
    desc: Lint code
    deps: [ .uv-locked ]
    cmds:
      - uv run ruff check {{.SOURCES}} {{.CLI_ARGS}}
      - uv run ruff format --check {{.SOURCES}}
    sources:
      - "**/*.py"
      - "pyproject.toml"
    generates:
      - ".ruff_cache/**/*"

  format:
    aliases: [ fmt ]
    desc: Format code
    deps: [ .uv-locked ]
    cmds:
      - uv run ruff check --fix {{.SOURCES}}
      - uv run ruff format {{.SOURCES}}
    sources:
      - "**/*.py"
      - "pyproject.toml"
    generates:
      - ".ruff_cache/**/*"

  typecheck:
    aliases: [ mypy ]
    desc: Type check code
    deps: [ .uv-locked ]
    cmds:
      - uv run mypy{{ if ne (env "MYPY_PRETTY") "0" }} --pretty{{end}} {{.SOURCES}}
    sources:
      - "**/*.py"
    generates:
      - ".mypy_cache/**/*"

  basedpyright:
    desc: Type check code with basedpyright
    deps: [ .uv ]
    cmds:
      - uv run basedpyright

  check:
    aliases: [ ci ]
    desc: Lint & typecheck python source files
    deps: [ lint, typecheck, basedpyright ]

  codespell:
    desc: Use Codespell to do spellchecking
    deps: [ .uv-locked ]
    cmd: uv run pre-commit run codespell --all-files

  pre-commit-all:
    desc: Run all pre-commit hooks against all files
    deps: [ .uv-locked ]
    silent: true
    cmd: uv run pre-commit run --verbose --all-files --hook-stage manual

  security-audit:
    desc: Audit dependencies for vulnerabilities
    deps: [ .uv-locked ]
    silent: true
    cmd: uv export --no-emit-project --no-header --no-annotate | uv run pip-audit --require-hashes --disable-pip -r /dev/stdin

  deptry:
    desc: Find unused, missing and transitive dependencies in project
    deps: [ .uv-locked ]
    cmd: uv run deptry .

  gitlint:
    desc: Lint git commit
    deps: [ .uv ]
    cmd: uv run gitlint {{.CLI_ARGS}}

  test:
    desc: Run tests
    deps: [ .uv ]
    cmd: uv run pytest {{.PYTEST_ARGS}} {{.CLI_ARGS}}

  test:cov:
    aliases: [ 'test:ci', 'test:all' ]
    desc: Run tests with coverage
    deps: [ .uv ]
    vars:
      PYTEST_ARGS: --cov --cov-report term
    cmds:
      - task: test
        vars:
          PYTEST_ARGS:
            ref: .PYTEST_ARGS

  all:
    desc: Run the full set of checks
    cmds:
      - task: check
      - task: codespell
      - task: test:cov

  clean:
    desc: Clear local caches and build artifacts
    cmds:
      - rm -rf `find . -name __pycache__`
      - rm -f `find . -type f -name '*.py[co]'`
      - rm -f `find . -type f -name '*~'`
      - rm -f `find . -type f -name '.*~'`
      - rm -rf `find . -name '.*cache'`
      - rm -rf .task
      - rm -rf htmlcov
      - rm -f .coverage
      - rm -f .coverage.*
      - rm -f coverage.xml
      - rm -rf *.egg-info
      - rm -rf build
      - rm -rf dist
      - rm -rf site
