from dishka import (
    DEFAULT_COMPONENT,
    AnyOf,
    AsyncContainer,
    FromComponent,
    FromDishka as Injected,
    Has,
    Marker,
    Scope,
    WithParents,
    activate,
    decorate,
)
from dishka.provider import BaseProvider

from waku.di._internal.providers import (
    Provider,
    activator,
    alias,
    contextual,
    from_context,
    is_registered,
    many,
    object_,
    provide,
    provide_all,
    provider,
    scoped,
    singleton,
    transient,
)

__all__ = [
    'DEFAULT_COMPONENT',
    'AnyOf',
    'AsyncContainer',
    'BaseProvider',
    'FromComponent',
    'Has',
    'Injected',
    'Marker',
    'Provider',
    'Scope',
    'WithParents',
    'activate',
    'activator',
    'alias',
    'contextual',
    'decorate',
    'from_context',
    'is_registered',
    'many',
    'object_',
    'provide',
    'provide_all',
    'provider',
    'scoped',
    'singleton',
    'transient',
]
