"""Generate the Extension SPI reference page from the SPI facades' ``__all__``.

The page is committed at ``docs/reference/extension-spi.md``; a pytest drift gate
(``tests/docs_drift/test_extension_spi_generated.py``) regenerates it in memory and asserts
byte-equality, so tier membership can never drift from code.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

__all__ = [
    'SPI_FACADES',
    'generate_spi_page',
    'main',
]

# The named SPI surfaces (pandas.api-style): each subpackage facade IS the SPI contract for the
# extension points it owns. Order is the page order.
SPI_FACADES: tuple[tuple[str, str], ...] = (
    ('waku.messaging.transport', 'Broker transports and the wire seam (mappers, metadata, dispositions).'),
    ('waku.messaging.transport.faststream', 'FastStream-based broker adapters and per-broker mapper contracts.'),
    ('waku.messaging.endpoints', 'The endpoint model and executor animated by routing.'),
    ('waku.messaging.durability', 'Messaging store-port contracts and the durability store composite.'),
    ('waku.messaging.sequence', 'Per-group durable sequence allocation contracts.'),
    ('waku.messaging.outbox', 'Outbox models and the relay.'),
    ('waku.messaging.inbox', 'Durable inbox models.'),
    ('waku.messaging.errors', 'Error policies, dead-letter models, replay, and the DLQ worker.'),
    ('waku.messaging.sending', 'Sending-failure policies applied by the outbox relay.'),
    ('waku.eventsourcing.store', 'Event store contracts (with snapshot/checkpoint facets); in-memory reference store.'),
    ('waku.eventsourcing.snapshot', 'Snapshot model, strategy, and migration contracts.'),
    ('waku.eventsourcing.projection', 'Projection contracts and polling configuration.'),
    ('waku.eventsourcing.serialization', 'Event and snapshot-state serializer contracts.'),
    ('waku.serialization', 'Payload codec and the upcasting toolkit.'),
    ('waku.backends.sqlalchemy', 'SQLAlchemy durability backend: entry point, store adapters, tables.'),
    ('waku.backends.memory', 'In-memory durability backend (whole-app wiring stub).'),
    ('waku.backends.testing', 'Backend-author conformance kit: assembly and facet contract suites.'),
    ('waku.extensions', 'Module and application lifecycle hooks.'),
)

_HEADER = """\
---
title: Extension SPI
description: The named SPI facades and the symbols extension authors implement against.
---

<!-- Generated by scripts/gen_spi_docs.py. Do not edit by hand: regenerate with
     `uv run python scripts/gen_spi_docs.py` (drift-gated by tests/docs_drift/test_extension_spi_generated.py). -->

# Extension SPI

Extension points — transports, stores, envelope mappers, projection locks, codecs, lifecycle
hooks — are carried by the subpackage facades below. The listed import path is the contract:
SPI symbols change on a shorter announced cycle than the public API (changelog plus one release),
and anything under an `_internal/` path is unversioned framework machinery with no stability
guarantee.
"""


def _facade_all(src_root: Path, dotted: str) -> tuple[str, ...]:
    rel = Path(*dotted.split('.')[1:]) / '__init__.py'
    tree = ast.parse((src_root / rel).read_text(encoding='utf-8'))
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if (
                    isinstance(target, ast.Name)
                    and target.id == '__all__'
                    and isinstance(node.value, (ast.List, ast.Tuple))
                ):
                    return tuple(
                        el.value for el in node.value.elts if isinstance(el, ast.Constant) and isinstance(el.value, str)
                    )
    msg = f'SPI facade {dotted} declares no __all__'
    raise ValueError(msg)


def generate_spi_page(src_root: Path) -> str:
    """Render the full markdown page for the SPI facades under ``src_root``."""
    sections = [_HEADER]
    for dotted, blurb in SPI_FACADES:
        names = _facade_all(src_root, dotted)
        listing = ' ·\n'.join(f'`{name}`' for name in names)
        sections.append(f'## `{dotted}`\n\n{blurb}\n\n{listing}\n')
    return '\n'.join(sections)


def main() -> int:
    """Regenerate docs/reference/extension-spi.md in place."""
    repo_root = Path(__file__).resolve().parents[1]
    page = generate_spi_page(repo_root / 'src' / 'waku')
    target = repo_root / 'docs' / 'reference' / 'extension-spi.md'
    target.write_text(page, encoding='utf-8')
    sys.stdout.write(f'wrote {target}\n')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
